spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: 1234
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
